<LblTxt@BoxLayout>:
    orientation: 'horizontal'      
    lblTxtIn: 'default'
    theTxt: iAmTxt
    Label:
        text: root.lblTxtIn
    TextInput:
        id: iAmTxt   
        size_hint:0.3,0.7   

<MyLayout@BoxLayout>:  
    orientation: 'vertical'
    LblTxt:   
        id: lt0
        lblTxtIn: 'Заработная плата:'

    LblTxt:   
        id: lt1
        lblTxtIn: 'Доход от аренды:'

    LblTxt:   
        id: lt2
        lblTxtIn: 'LblTxtInput2'
    LblTxt:   
        id: lt3
        lblTxtIn: '123'
    LblTxt:   
        id: lt4
        lblTxtIn: '123'
    LblTxt:   
        id: lt5
        lblTxtIn: 'Если Вы не работаете, укажите ту часть заработной платы родителей,\n которая покрывает лично Ваши расходы'
    LblTxt:   
        id: lt6
        lblTxtIn: '123'
    LblTxt:   
        id: lt7
        lblTxtIn: '123'
    LblTxt:   
        id: lt8
        lblTxtIn: '123'
    LblTxt:   
        id: lt9
        lblTxtIn: '123'

MyLayout