# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1235, 905)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 780, 611, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 780, 621, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.inpWage = QtWidgets.QLineEdit(self.centralwidget)
        self.inpWage.setGeometry(QtCore.QRect(290, 180, 113, 32))
        self.inpWage.setText("")
        self.inpWage.setObjectName("inpWage")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 140, 331, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 190, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 240, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 300, 121, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 350, 281, 61))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 440, 121, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 500, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 580, 161, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(690, 140, 331, 20))
        self.label_9.setObjectName("label_9")
        self.inpParrentWage = QtWidgets.QLineEdit(self.centralwidget)
        self.inpParrentWage.setGeometry(QtCore.QRect(290, 240, 113, 32))
        self.inpParrentWage.setText("")
        self.inpParrentWage.setObjectName("inpParrentWage")
        self.inpRent = QtWidgets.QLineEdit(self.centralwidget)
        self.inpRent.setGeometry(QtCore.QRect(290, 290, 113, 32))
        self.inpRent.setText("")
        self.inpRent.setObjectName("inpRent")
        self.inpAllowance = QtWidgets.QLineEdit(self.centralwidget)
        self.inpAllowance.setGeometry(QtCore.QRect(340, 360, 113, 32))
        self.inpAllowance.setText("")
        self.inpAllowance.setObjectName("inpAllowance")
        self.inpCashback = QtWidgets.QLineEdit(self.centralwidget)
        self.inpCashback.setGeometry(QtCore.QRect(260, 430, 113, 32))
        self.inpCashback.setText("")
        self.inpCashback.setObjectName("inpCashback")
        self.inpSaving = QtWidgets.QLineEdit(self.centralwidget)
        self.inpSaving.setGeometry(QtCore.QRect(240, 490, 113, 32))
        self.inpSaving.setText("")
        self.inpSaving.setObjectName("inpSaving")
        self.anotherIncome = QtWidgets.QLineEdit(self.centralwidget)
        self.anotherIncome.setGeometry(QtCore.QRect(250, 570, 113, 32))
        self.anotherIncome.setText("")
        self.anotherIncome.setObjectName("anotherIncome")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1235, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Сбросить"))
        self.pushButton_2.setText(_translate("MainWindow", "Рассчитать"))
        self.label.setText(_translate("MainWindow", "- Ваш ежемесячный доход:"))
        self.label_2.setText(_translate("MainWindow", "Заработная плата"))
        self.label_3.setText(_translate("MainWindow", "ЗП родителей"))
        self.label_4.setText(_translate("MainWindow", "Доход от аренды"))
        self.label_5.setText(_translate("MainWindow", "Пособие или иная социальная выплата"))
        self.label_6.setText(_translate("MainWindow", "Пассивный доход"))
        self.label_7.setText(_translate("MainWindow", "Сбережения"))
        self.label_8.setText(_translate("MainWindow", "Иной источник дохода"))
        self.label_9.setText(_translate("MainWindow", "- Ваш ежемесячный расход:"))

